# Generated by Django 3.2.3 on 2021-05-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='message',
        ),
        migrations.AddField(
            model_name='customers',
            name='age',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
