# Generated by Django 3.2.3 on 2021-05-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20210531_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='sex',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=100),
        ),
    ]
