# Generated by Django 3.2.3 on 2021-05-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customers_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='Churn',
            field=models.CharField(choices=[('Loyal', 'Loyal'), ('to be churned', 'To Be Churned'), ('churned', 'Churned')], default=('to be churned', 'To Be Churned'), max_length=100),
        ),
    ]
