# Generated by Django 3.2.3 on 2021-05-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customers_churn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Churn',
            field=models.CharField(choices=[('Loyal', 'Loyal'), ('to be churned', 'To Be Churned'), ('churned', 'Churned')], default=('Loyal', 'Loyal'), max_length=100),
        ),
    ]
